### ISSUE TITLE
Install Fail on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by YoungWilliamZ** [jabley/homebrew-wrk2#4]
After typing the instructions, I get the following:

```
➜  ~ brew install --HEAD wrk2
==> Installing wrk2 from jabley/wrk2
==> Cloning https://github.com/giltene/wrk2.git
Updating /Users/williamz/Library/Caches/Homebrew/wrk2--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 44a94c1 Merge pull request #80 from giltene/jr/status
==> make
Last 15 lines from /Users/williamz/Library/Logs/Homebrew/wrk2/01.make:
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_bcdef.h
BUILDVM   lj_ffdef.h
BUILDVM   lj_vm.s
BUILDVM   lj_folddef.h
BUILDVM   lj_recdef.h
BUILDVM   lj_libdef.h
BUILDVM   jit/vmdef.lua
make[1]: *** [lj_folddef.h] Segmentation fault: 11
make[1]: *** Deleting file `lj_folddef.h'
make[1]: *** Waiting for unfinished jobs....
make: *** [deps/luajit/src/libluajit.a] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jabley/homebrew-wrk2/issues
```

It seems like that `lj_folddef.h` is not suitable, and I try to solve it by google but I can't find a good solution.

From [here](https://github.com/neovim/neovim/issues/11192), I found a [discussion](https://forums.developer.apple.com/thread/121887) on that.

Please pay attention to this bug. And any possible solution is great for me.

**Comment by dakango** [comment]
+1

**Comment by chien-le** [comment]
+1

**Comment by kmjones1979** [comment]
+1

**Comment by PumpMagic** [comment]
For those willing to build from source, there's a tweak to the wrk2 build command that addresses this. Run `brew install openssl`, clone the wrk2 repo, navigate to its directory, and run `make MACOSX_DEPLOYMENT_TARGET=10.14`. If all goes well, you can then invoke it with `./wrk`.

For more details, see the wrk2 wiki. It doesn't currently call out this build failure specifically, but it does recommend the `MACOSX_DEPLOYMENT_TARGET` tweak for another problem. https://github.com/giltene/wrk2/wiki/Installing-wrk2-on-Mac

**Comment by apai05** [comment]
the above solution does not seem to work

**Comment by jabley** [comment]
Homebrew supports Big Sur or above right now. So Catalina isn't supported.

I've installed wrk2 using this tap on Big Sur and Monterey, so considering this closed. Please reopen if you're still having problems on new MacOS.
