### ISSUE TITLE
Homebrew installation fails on macos - luajit: cannot create state: not enough memory

### ISSUE THREAD

**Issue by nitinsurana** [jabley/homebrew-wrk2#5]
<img width="590" alt="Screenshot 2020-06-07 at 06 52 05" src="https://user-images.githubusercontent.com/7137160/83970599-682e3280-a88b-11ea-82aa-f7d0c9c9cf47.png">

Related - https://github.com/LuaJIT/LuaJIT/issues/521

**Comment by MarsonShine** [comment]
same problem
<img width="558" alt="截屏2020-11-26下午8 17 55" src="https://user-images.githubusercontent.com/17610342/100350215-80099680-3024-11eb-9536-5931ad4ada0c.png">
macOS Catalina 10.15.3

**Comment by jabley** [comment]
I think this was fixed in Homebrew/homebrew-core#46928
